### ISSUE TITLE
Docker image is not being updated

### ISSUE THREAD

**Issue by parasiteoflife** [AzamServer/pihole-doh#4]
The readme says that the image should update whenever main pihole is updated, official image has been updated 2 months ago and pihole-doh 4 months ago.

**Comment by transfairs** [comment]
A rebuild helped for me to get the latest pihole image. For this, I cloned the project into the portainer data folder of pihole-doh, e.g., `./data/compose/7`. (If pihole-doh was your seventh stack.)

I used a simplified version of `Dockerfile` to pull the image, then came back to the original file as I had some issues with the `RUN` commands using Portainer. Here is the simplified version to update the image:

````
FROM pihole/pihole
MAINTAINER ali azam <ali@azam.email>
EXPOSE 53:53/tcp 53:53/udp 67:67/udp 80:80/tcp
````

In Portainer, I added the `build` part to the docker-compose entry:

```
services:
  pihole-doh:
    container_name: pihole-doh
    build:
      context: ./pihole-doh
    image: azamserver/pihole-doh:latest
    restart: unless-stopped
    ports:
       ...

```

Let it run and deploy, verified new pihole version, removed the `build` part, redeployed, and deleted the folder in `./data/compose/7`. Done.

Happy to hear about easier approaches.
